// Builds the single distributed index.html from src/, styles/main.css and template.html.
// Node-only (no framework) — esbuild is the one devDependency, used solely to bundle the
// ES modules under src/ into one IIFE script. Nothing here ships to the browser except
// plain HTML/CSS/JS: this script never runs at runtime, only at build time.
import { build, context } from 'esbuild';
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const watch = process.argv.includes('--watch');

const HEADER = '<!-- AUTO-GENERATED by scripts/build.mjs from src/ + styles/ + template.html — do not edit directly. Edit the sources, then run `npm run build`. -->\n';

async function assemble() {
  const [template, css, jsResult] = await Promise.all([
    readFile(path.join(root, 'template.html'), 'utf8'),
    readFile(path.join(root, 'styles/main.css'), 'utf8'),
    build({
      entryPoints: [path.join(root, 'src/main.js')],
      bundle: true,
      format: 'iife',
      write: false,
      logLevel: 'warning',
    }),
  ]);
  const js = jsResult.outputFiles[0].text;
  const html = HEADER + template.split('{{STYLES}}').join(css).split('{{SCRIPT}}').join(js);
  await writeFile(path.join(root, 'index.html'), html);
  console.log('[build] wrote index.html');
}

if (watch) {
  const ctx = await context({
    entryPoints: [path.join(root, 'src/main.js')],
    bundle: true,
    format: 'iife',
    write: false,
    logLevel: 'warning',
    plugins: [{
      name: 'reassemble-html',
      setup(b) {
        b.onEnd(async (result) => {
          if (result.errors.length) return;
          const [template, css] = await Promise.all([
            readFile(path.join(root, 'template.html'), 'utf8'),
            readFile(path.join(root, 'styles/main.css'), 'utf8'),
          ]);
          const js = result.outputFiles[0].text;
          const html = HEADER + template.split('{{STYLES}}').join(css).split('{{SCRIPT}}').join(js);
          await writeFile(path.join(root, 'index.html'), html);
          console.log('[watch] rebuilt index.html —', new Date().toLocaleTimeString());
        });
      },
    }],
  });
  await ctx.watch();
  console.log('[watch] watching src/ — Ctrl+C to stop (styles/ and template.html need a manual rebuild if edited)');
} else {
  await assemble();
}
